### ISSUE TITLE
下拉刷新，refresh不起作用

### ISSUE THREAD

**Issue by longtimett** [DDFE/DDFE-blog#19]
this.scroll.refresh()
//Unresolved function or method refresh()    (编辑器显示)
||代码如下：
 methods: {
        loadData() {
          this.$http.get('/api/dinners').then((response) => {
            this.data = response.body.data.concat(this.data)
            this.$nextTick(() => {
              let wrapper = document.querySelector('.wrapper')
              let scroll = new Bscroll(wrapper, {})
              if (!this.scroll) {
                this.scroll = new Bscroll(this.$refs.wrapper, {})
                  probeType: 3,

                this.scroll.on('touchend', (pos) => {
                  // 下拉动作
                  if (pos.y > 50) {
                    this.loadData()
                  }
                })
              } else {
                this.scroll.refresh();
              }
            })
          })
        }}

**Comment by dolymood** [comment]
这个问题不要在这里提
