### ISSUE TITLE
probeType为3时触发频率问题

### ISSUE THREAD

**Issue by Camellia55** [DDFE/DDFE-blog#32]
一开始仿照better-scroll+vue使用的probeType为1，上拉加载的时候，依次提示“上拉加载更多”、“释放刷新”、“数据加载完成”，文字切换正常；
后面应为要实现固定头行和头列的滚动table，必须probeType为3，实时计算头行和头列的移动距离保持其在页面上的位置不变，但是文字提示就没办法正常了。原因是一直触发“scroll”事件，scroll事件中提示文案是“释放刷新”。所以，不管怎么滚动提示文字都是“释放刷新”，但其实它是有依次切换文案了，因为看不到变化的过程，且最后都是“释放刷新”。
有遇到类似的问题吗？或者说说probeType为3时触发频率是咋样的？

**Comment by dolymood** [comment]
better scroll 官方群了解一波

**Comment by ailaiwuyou** [comment]
> 一开始仿照better-scroll+vue使用的probeType为1，上拉加载的时候，依次提示“上拉加载更多”、“释放刷新”、“数据加载完成”，文字切换正常；
> 后面应为要实现固定头行和头列的滚动table，必须probeType为3，实时计算头行和头列的移动距离保持其在页面上的位置不变，但是文字提示就没办法正常了。原因是一直触发“scroll”事件，scroll事件中提示文案是“释放刷新”。所以，不管怎么滚动提示文字都是“释放刷新”，但其实它是有依次切换文案了，因为看不到变化的过程，且最后都是“释放刷新”。
> 有遇到类似的问题吗？或者说说probeType为3时触发频率是咋样的？

遇到了，请问是怎么解决的
